apiVersion: v1
kind: Service
metadata:
  name: blogsearch-service
spec:
  type: NodePort
  selector:
    app: blogsearch
  ports:
    - protocol: TCP
      port: 8000      
      targetPort: 8000
      nodePort: 32000
  
