services:
  meili:
    image: getmeili/meilisearch:v1.14
    container_name: meili-dev
    env_file: .env
    volumes:
      - ./meili_data:/meili_data
    ports: ["0.0.0.0:7800:7700"]

  blogsearch:
    build: .
    depends_on: [meili]
    container_name: blogsearch-dev
    env_file: .env
    volumes:
      - .:/app
      - ./web:/app/web
    ports: ["0.0.0.0:7801:8000"]

