services:
  meili-dev:
    image: getmeili/meilisearch:v1.14
    container_name: meili-dev
    env_file: .env
    volumes:
      - ./.meili_data:/meili_data
    ports: ["0.0.0.0:8001:7700"]

  blogsearch-dev:
    build: .
    depends_on: [meili-dev]
    container_name: blogsearch-dev
    env_file: .env
    volumes:
      - .:/app
      - ./web:/app/web
    ports: ["0.0.0.0:8000:8000"]

