services:
  db:
    image: postgres:17
    container_name: pg
    restart: unless-stopped
    env_file: .env
    volumes:
      - /srv/pgdata:/var/lib/postgresql/data
    ports: ["127.0.0.1:5432:5432"]

  meili:
    image: getmeili/meilisearch:v1.14
    container_name: meili
    restart: unless-stopped
    env_file: .env
    volumes:
      - /srv/meili_data:/meili_data
    ports: ["0.0.0.0:7700:7700"]

  app:
    build: .
    depends_on: [db, meili]
    container_name: blogsearch
    restart: unless-stopped
    env_file: .env
    ports: ["0.0.0.0:7701:8000"]

  adminer:
    image: adminer
    container_name: adminer
    ports: ["0.0.0.0:7702:8080"]
