"""Integration tests: TEST_DATABASE_URL must point to disposable PostgreSQL.

Run: .venv/bin/python -m unittest discover -s tests -p test_storage.py -v
Every test creates and drops its own schema; DATABASE_URL is never used.
"""

import json
import multiprocessing
import os
import time
import unittest
from concurrent.futures import ThreadPoolExecutor
from datetime import date, timedelta
from hashlib import sha256
from threading import Barrier, Event
from unittest.mock import patch
from uuid import uuid4

import psycopg2
from psycopg2 import sql
from psycopg2.extensions import make_dsn
from psycopg2.extras import RealDictCursor

from scraper.storage import Store


TEST_DATABASE_URL = os.environ.get('TEST_DATABASE_URL')


def claim_in_process(dsn, barrier, results):
    """Spawned workers construct independent connection pools."""
    try:
        with Store(dsn) as store:
            barrier.wait(timeout=15)
            results.put(store.claim())
    except Exception as error:
        results.put({'error': type(error).__name__})


@unittest.skipUnless(TEST_DATABASE_URL, 'TEST_DATABASE_URL is not set')
class StorageTests(unittest.TestCase):
    def setUp(self):
        self.schema = 'test_storage_' + uuid4().hex
        self.dsn = make_dsn(TEST_DATABASE_URL, options='-csearch_path=' + self.schema)
        self.connection = psycopg2.connect(self.dsn)
        self.connection.autocommit = True
        self.addCleanup(self.connection.close)
        self.query(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(self.schema)))
        self.addCleanup(self.drop_schema)
        self.store = Store(self.dsn)
        self.addCleanup(self.store.close)
        self.store.migrate()

    def drop_schema(self):
        # The identifier is generated by this test, never an environment-provided schema.
        self.query(sql.SQL('DROP SCHEMA {} CASCADE').format(sql.Identifier(self.schema)))

    def query(self, statement, parameters=()):
        with self.connection.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(statement, parameters)
            return [dict(row) for row in cursor.fetchall()] if cursor.description else []

    def job(self, name='article', kind='page', **extra):
        return {'kind': kind, 'url': 'https://' + name + '.example/post', **extra}

    def page(self, url='https://article.example/post', **extra):
        return {'title': 'A post', 'url': url, 'fingerprint': 'first-fingerprint',
                'date': date(2026, 1, 2), 'text': 'The body of the post.', **extra}

    def claimed(self, **extra):
        self.store.enqueue([self.job(**extra)])
        return self.store.claim(1)[0]

    def row(self, job):
        return self.query('SELECT * FROM crawl_jobs WHERE id = %s', (job['id'],))[0]

    def make_due(self, job):
        self.query("UPDATE crawl_jobs SET due_at = NOW() - INTERVAL '1 second' WHERE id = %s",
                   (job['id'],))

    def expire(self, job):
        self.query("UPDATE crawl_jobs SET lease_until = NOW() - INTERVAL '1 second' WHERE id = %s",
                   (job['id'],))

    def save(self, page=None):
        job = self.claimed()
        self.assertTrue(self.store.complete(job, page=page or self.page()))
        return job, self.store.index_batch()[0]

    def assert_delay(self, job, seconds):
        row = self.query('SELECT EXTRACT(EPOCH FROM due_at - NOW()) AS delay FROM crawl_jobs WHERE id = %s',
                         (job['id'],))[0]
        self.assertAlmostEqual(float(row['delay']), seconds, delta=5)

    def test_explicit_migration_is_idempotent_and_preserves_existing_pages(self):
        self.query("""INSERT INTO pages (title, url, fingerprint, date, text)
                      VALUES ('Legacy', 'https://legacy.example/', 'legacy', '2020-01-01', 'Old text')""")
        before = self.query('SELECT * FROM pages')
        self.store.migrate()
        self.store.migrate()
        self.assertEqual(before, self.query('SELECT * FROM pages'))
        self.assertEqual([], self.store.index_batch())
        with self.assertRaises(psycopg2.IntegrityError):
            self.query("INSERT INTO pages (url, fingerprint) VALUES ('https://legacy.example/', 'another-body')")
        self.query("INSERT INTO pages (url, fingerprint) VALUES ('https://distinct.example/', 'legacy')")
        self.query('DROP TABLE crawl_job_sources')
        self.query('DROP TABLE crawl_jobs')
        with Store(self.dsn):
            self.assertIsNone(self.query("SELECT to_regclass('crawl_jobs') AS table_name")[0]['table_name'])
        self.store.migrate()

    def test_dsn_resolution_and_context_closing(self):
        with patch('scraper.storage.ThreadedConnectionPool') as pool:
            with patch.dict(os.environ, {'DATABASE_URL': 'environment-dsn'}):
                Store('explicit-dsn')
                pool.assert_called_with(1, 4, dsn='explicit-dsn', connect_timeout=10)
                Store()
                pool.assert_called_with(1, 4, dsn='environment-dsn', connect_timeout=10)
            with patch.dict(os.environ, {}, clear=True):
                Store()
                pool.assert_called_with(1, 4, dsn='', connect_timeout=10)
        with Store(self.dsn) as store:
            self.assertEqual(1, store._pool.minconn)
            self.assertEqual(4, store._pool.maxconn)
            store.status()
        self.assertTrue(store._pool.closed)
        store.close()

    def test_migration_upgrades_legacy_domains_and_preserves_feed_checks(self):
        self.query('DROP TABLE domains')
        self.query('''CREATE TABLE domains (
            domain TEXT PRIMARY KEY, last_feed_check DATE,
            date_added TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )''')
        self.query("INSERT INTO domains (domain, last_feed_check) VALUES ('article.example', '2025-04-01')")
        before = self.query('SELECT domain, last_feed_check, date_added FROM domains')

        self.store.migrate()
        self.store.migrate()
        self.assertEqual(before, self.query('SELECT domain, last_feed_check, date_added FROM domains'))
        self.assertIsNone(self.query('SELECT next_allowed_scrape FROM domains')[0]['next_allowed_scrape'])

        job = self.claimed()
        self.store.fail(job, 'HTTP status 429', status_code=429)
        cooldown = self.query('SELECT next_allowed_scrape > NOW() AS paused FROM domains')[0]
        self.assertTrue(cooldown['paused'])
        self.assertEqual([], self.store.claim())

    def test_connection_and_statement_timeouts_and_cancel_recovery(self):
        with self.store._transaction() as cursor:
            self.assertEqual('10', cursor.connection.get_dsn_parameters()['connect_timeout'])
            cursor.execute('SHOW statement_timeout')
            self.assertEqual('30s', cursor.fetchone()['statement_timeout'])
        with self.assertRaises(psycopg2.errors.QueryCanceled):
            with self.store._transaction() as cursor:
                cursor.execute("SET LOCAL statement_timeout = '20ms'")
                cursor.execute('SELECT pg_sleep(0.1)')
        self.assertEqual(1, self.store.enqueue([self.job()]))

    def test_dead_idle_connection_is_replaced_before_work(self):
        with self.store._transaction() as cursor:
            cursor.execute('SELECT pg_backend_pid() AS pid')
            old_pid = cursor.fetchone()['pid']
        self.query('SELECT pg_terminate_backend(%s)', (old_pid,))
        self.assertEqual(1, self.store.enqueue([self.job()]))
        with self.store._transaction() as cursor:
            cursor.execute('SELECT pg_backend_pid() AS pid')
            self.assertNotEqual(old_pid, cursor.fetchone()['pid'])
        self.assertEqual({}, self.store._pool._used)

    def test_connection_loss_during_completion_rolls_back_and_is_not_replayed(self):
        job = self.claimed()
        before = self.row(job)
        original = self.store._save_page
        def disconnect(cursor, page, **kwargs):
            result = original(cursor, page, **kwargs)
            self.query('SELECT pg_terminate_backend(%s)', (cursor.connection.get_backend_pid(),))
            return result
        with patch.object(self.store, '_save_page', side_effect=disconnect) as save:
            with self.assertRaises((psycopg2.OperationalError, psycopg2.InterfaceError)):
                self.store.complete(job, page=self.page(), links=[self.job('new')])
            self.assertEqual(1, save.call_count)
        self.assertEqual(before, self.row(job))
        self.assertEqual([], self.store.index_batch())
        self.assertEqual([], self.query('SELECT * FROM pages'))
        self.assertEqual(1, len(self.query('SELECT * FROM crawl_jobs')))
        self.assertTrue(self.store.complete(job, page=self.page()))

    def test_batch_enqueue_counts_only_new_jobs_and_keeps_progress(self):
        payload = {'root': 'https://root.example/', 'depth': 2}
        jobs = [self.job(str(number), payload=payload) for number in range(510)]
        self.assertEqual(510, self.store.enqueue(jobs + [jobs[0]]))
        active = self.store.claim(1)[0]
        self.assertEqual(payload, active['payload'])
        before = self.row(active)
        self.assertEqual(0, self.store.enqueue([{**job, 'priority': 7, 'payload': {'depth': 0}} for job in jobs]))
        self.assertEqual(before, self.row(active))
        pending = self.query("SELECT priority, payload FROM crawl_jobs WHERE status = 'pending'")
        self.assertTrue(all(row['priority'] == 7 and row['payload'] == payload for row in pending))
        self.assertEqual(0, self.store.enqueue([]))
        self.assertEqual(1, self.store.enqueue([self.job('same'), self.job('same', priority=9)]))
        self.assertEqual(9, self.query("SELECT priority FROM crawl_jobs WHERE url = 'https://same.example/post'")[0]['priority'])

    def test_rediscovery_preserves_terminal_states_and_delayed_retries(self):
        for status in ('done', 'skipped', 'failed', 'pending'):
            self.store.enqueue([self.job(status)])
            self.query("""UPDATE crawl_jobs SET status = %s, attempts = 5, error = 'old error',
                          etag = 'old tag', due_at = NOW() + INTERVAL '2 days' WHERE url = %s""",
                       (status, self.job(status)['url']))
        before = self.query('SELECT * FROM crawl_jobs ORDER BY id')
        self.assertEqual(0, self.store.enqueue([self.job(row['status']) for row in before]))
        self.assertEqual(before, self.query('SELECT * FROM crawl_jobs ORDER BY id'))

    def source(self, name):
        return self.job(name, kind='feed', priority=100)

    def test_source_removal_pauses_descendants_and_preserves_saved_content(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a, b])
        feeds = {task['url']: task for task in self.store.claim(2)}
        child = self.job('history', payload={'root': 'https://history.example/'})
        self.store.complete(feeds[a['url']], links=[child])
        self.store.complete(feeds[b['url']])
        active = self.store.claim(1)[0]
        self.store.complete(active, page=self.page(url=child['url']))
        before = self.query('SELECT * FROM pages')
        self.make_due(active)
        self.store.reconcile_sources([b], allow_large_removal=True)
        self.assertEqual(self.store.claim(), [])
        self.assertEqual(self.query('SELECT * FROM pages'), before)
        self.assertEqual(self.store.status()['source_paused_jobs'], 2)
        self.assertEqual(self.store.status()['due'], 0)
        self.assertEqual(self.store.status()['sources'], {'active': 1, 'inactive': 1})

    def test_pilot_sync_does_not_remove_other_sources_but_does_exclude_comics(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a])
        self.store.reconcile_sources([b], replace=False)
        self.assertEqual(self.store.status()['sources']['active'], 2)
        self.store.reconcile_sources([b], excluded=[a['url']], replace=False)
        self.assertEqual(self.store.status()['sources']['active'], 1)
        self.assertEqual([task['url'] for task in self.store.claim()], [b['url']])
        self.assertEqual(self.query('SELECT reason FROM crawl_sources WHERE feed_url = %s', (a['url'],))[0]['reason'], 'comic')

    def test_suspicious_source_drop_rolls_back_the_entire_sync(self):
        originals = [self.source(str(number)) for number in range(10)]
        self.store.reconcile_sources(originals)
        before = self.query('SELECT * FROM crawl_sources ORDER BY feed_url')
        jobs = self.query('SELECT * FROM crawl_jobs ORDER BY id')
        with self.assertRaises(ValueError):
            self.store.reconcile_sources([self.source('new')])
        self.assertEqual(self.query('SELECT * FROM crawl_sources ORDER BY feed_url'), before)
        self.assertEqual(self.query('SELECT * FROM crawl_jobs ORDER BY id'), jobs)
        self.store.reconcile_sources(originals[:8])  # Exactly 20% is allowed.
        self.assertEqual(self.store.status()['sources']['inactive'], 2)

    def test_returning_source_is_immediately_rechecked_without_deleting_progress(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a, b])
        feeds = {task['url']: task for task in self.store.claim(2)}
        for task in feeds.values():
            self.store.complete(task, etag='old')
        self.store.reconcile_sources([b], allow_large_removal=True)
        self.store.reconcile_sources([a, b])
        again = self.store.claim(1)[0]
        self.assertEqual(again['id'], feeds[a['url']]['id'])
        self.assertIsNone(again['etag'])

    def test_shared_page_stays_active_when_one_source_is_removed(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a, b])
        child = self.job('shared', priority=90)
        for task in self.store.claim(2):
            self.store.complete(task, links=[child])
        self.store.reconcile_sources([b], excluded=[a['url']])
        task = self.store.claim(1)[0]
        self.assertEqual(task['url'], child['url'])
        self.assertTrue(self.store.complete(task, page=self.page(url=child['url'])))
        self.assertEqual(len(self.store.index_batch()), 1)

    def test_source_removed_during_fetch_cannot_commit_results_or_release_host_early(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a, b])
        feeds = {task['url']: task for task in self.store.claim(2)}
        active = feeds[a['url']]
        before = self.row(active)
        self.store.reconcile_sources([b], excluded=[a['url']])
        self.assertEqual(self.row(active)['lease_token'], before['lease_token'])
        self.assertEqual(self.row(active)['status'], 'running')
        child = self.job('old')
        self.assertFalse(self.store.complete(active, links=[child], page=self.page()))
        self.assertEqual(self.query('SELECT * FROM pages'), [])
        self.assertEqual(self.query("SELECT id FROM crawl_jobs WHERE kind = 'page'"), [])
        self.assertEqual(self.row(active)['status'], 'pending')

    def test_removed_source_failure_does_not_pause_an_active_source_host(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a, b])
        feeds = {task['url']: task for task in self.store.claim(2)}
        self.store.reconcile_sources([b], excluded=[a['url']])
        self.assertFalse(self.store.fail(feeds[a['url']], 'rate limit', status_code=429, retry_after=120))
        self.assertEqual(self.query('SELECT * FROM domains'), [])

    def test_shared_archive_is_revisited_so_descendants_gain_the_new_source(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a, b])
        feeds = {task['url']: task for task in self.store.claim(2)}
        root = 'https://shared.example/'
        archive = self.job('shared', kind='archive', priority=20, payload={'root': root})
        child = self.job('old', payload={'root': root})
        self.store.complete(feeds[a['url']], links=[archive])
        first = self.store.claim(1)[0]
        self.store.complete(first, links=[child], etag='cached')
        self.store.complete(feeds[b['url']], links=[archive])
        self.store.reconcile_sources([b], excluded=[a['url']])
        repeated = self.store.claim(1)[0]
        self.assertEqual(repeated['id'], first['id'])
        self.assertIsNone(repeated['etag'])
        self.store.complete(repeated, links=[child])
        self.assertEqual(self.store.claim(1)[0]['url'], child['url'])

    def test_shared_archive_304_in_flight_is_revisited_with_new_source(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a, b])
        feeds = {task['url']: task for task in self.store.claim(2)}
        archive = self.job('shared', kind='archive', payload={'root': 'https://shared.example/'})
        self.store.complete(feeds[a['url']], links=[archive])
        first = self.store.claim(1)[0]
        self.store.complete(first, etag='cached')
        self.make_due(first)
        running = self.store.claim(1)[0]
        self.store.complete(feeds[b['url']], links=[archive])
        self.store.complete(running, not_modified=True)
        again = self.store.claim(1)[0]
        self.assertEqual(again['id'], running['id'])
        self.assertIsNone(again['etag'])

    def test_shared_skipped_discovery_page_can_propagate_its_new_source(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a, b])
        feeds = {task['url']: task for task in self.store.claim(2)}
        listing = self.job('shared', payload={'root': 'https://shared.example/'})
        self.store.complete(feeds[a['url']], links=[listing])
        first = self.store.claim(1)[0]
        self.store.complete(first, skip_reason='no_extractable_text')
        self.store.complete(feeds[b['url']], links=[listing])
        self.store.reconcile_sources([b], excluded=[a['url']])
        self.assertEqual(self.store.claim(1)[0]['id'], first['id'])

    def test_manual_jobs_remain_independent_and_missing_source_rolls_back(self):
        independent = self.job('manual')
        self.store.enqueue([independent])
        self.store.reconcile_sources([self.source('a')])
        self.assertTrue(self.query("SELECT manual FROM crawl_jobs WHERE kind = 'page'")[0]['manual'])
        with self.assertRaises(psycopg2.IntegrityError):
            self.store.enqueue([{**self.job('orphan'), 'manual': False, 'source_urls': ['missing']}])
        self.assertEqual(len(self.query('SELECT * FROM crawl_jobs')), 2)

    def test_retry_commands_cannot_reactivate_removed_source_work(self):
        a, b = self.source('a'), self.source('b')
        self.store.reconcile_sources([a, b])
        feeds = {task['url']: task for task in self.store.claim(2)}
        self.store.complete(feeds[b['url']])
        self.store.complete(feeds[a['url']], links=[self.job('old')])
        task = self.store.claim(1)[0]
        self.store.fail(task, 'HTTP 404', retryable=False)
        self.store.reconcile_sources([b], excluded=[a['url']])
        self.store.retry_failed()
        self.store.retry_skipped()
        self.assertEqual(self.store.claim(), [])

    def test_shallower_discovery_reopens_depth_cutoff_without_charging_again(self):
        payload = {'root': 'https://article.example/', 'depth': 5}
        original = self.job(payload=payload)
        self.store.enqueue([original])
        task = self.store.claim(1)[0]
        self.store.complete(task, skip_reason='no_extractable_text', etag='old')
        self.assertEqual(0, self.store.enqueue([{**original, 'payload': {**payload, 'depth': 1}}]))
        updated = self.row(task)
        self.assertEqual(updated['payload']['depth'], 1)
        self.assertEqual(updated['status'], 'pending')
        self.assertIsNone(updated['etag'])
        self.assertEqual(self.store.status()['backfill']['discovered'], 1)
        self.assertEqual(self.store.claim(1)[0]['id'], task['id'])

    def test_running_shallower_discovery_keeps_lease_then_revisits_with_full_body(self):
        payload = {'root': 'https://article.example/', 'depth': 5}
        original = self.job(kind='archive', payload=payload)
        self.store.enqueue([original])
        task = self.store.claim(1)[0]
        self.store.enqueue([{**original, 'payload': {**payload, 'depth': 0}}])
        self.assertEqual(self.row(task)['lease_token'], str(task['lease_token']))
        self.assertEqual(self.row(task)['status'], 'running')
        self.assertTrue(self.store.complete(task, etag='stale-depth-response'))
        self.assertIsNone(self.row(task)['etag'])
        again = self.store.claim(1)[0]
        self.assertEqual(again['payload']['depth'], 0)
        self.store.complete(again, etag='fresh')
        self.assertEqual(self.store.claim(1), [])

    def test_shallower_discovery_preserves_terminal_failure_and_retry_time(self):
        payload = {'root': 'https://article.example/', 'depth': 5}
        original = self.job(payload=payload)
        self.store.enqueue([original])
        task = self.store.claim(1)[0]
        self.store.fail(task, 'retry later')
        before = self.row(task)
        self.store.enqueue([{**original, 'payload': {**payload, 'depth': 2}}])
        after = self.row(task)
        self.assertEqual(after['due_at'], before['due_at'])
        self.assertEqual(after['attempts'], before['attempts'])
        self.assertEqual(after['payload']['depth'], 2)
        self.make_due(task)
        task = self.store.claim(1)[0]
        self.store.fail(task, 'HTTP 404', retryable=False)
        before = self.row(task)
        self.store.enqueue([{**original, 'payload': {**payload, 'depth': 0}}])
        self.assertEqual(self.row(task), before)

    def test_best_depth_within_batch_and_invalid_depth_rolls_back(self):
        payload = {'root': 'https://article.example/', 'depth': 5}
        original = self.job(payload=payload)
        self.store.enqueue([original, {**original, 'payload': {**payload, 'depth': 1}}])
        self.assertEqual(self.store.claim(1)[0]['payload']['depth'], 1)
        for depth in (-1, '1', True):
            with self.assertRaises(ValueError):
                self.store.enqueue([self.job('invalid', payload={'depth': depth})])

    def test_feed_pagination_is_scoped_budgeted_and_not_checked_daily(self):
        root = 'https://example.org/'
        self.store.set_backfill_budget(root, 1)
        task = self.job(kind='feed_page', payload={'root': root, 'depth': 1}, priority=40)
        self.assertEqual(1, self.store.enqueue([task]))
        self.assertEqual(0, self.store.enqueue([{**task, 'url': 'https://other.example/feed?page=3'}]))
        active = self.store.claim(1)[0]
        self.assertEqual(self.row(active)['scope'], sha256(root.encode()).hexdigest())
        self.store.complete(active, etag='old')
        self.assert_delay(active, 30 * 86400)
        report = self.store.status(root=root)
        self.assertEqual(report['site']['coverage'], 'budget_limited')
        self.assertEqual(report['site']['visited'], 1)
        self.assertEqual(report['site']['due'], 0)
        self.store.set_backfill_budget(root, 2)
        self.assertEqual(self.store.claim(1)[0]['id'], active['id'])

    def test_migration_extends_legacy_kind_constraint_without_losing_jobs(self):
        task = self.claimed()
        self.query('ALTER TABLE crawl_jobs DROP CONSTRAINT crawl_jobs_kind_check')
        self.query("ALTER TABLE crawl_jobs ADD CONSTRAINT crawl_jobs_kind_check CHECK (kind IN ('feed', 'page', 'sitemap', 'archive'))")
        before = self.row(task)
        self.store.migrate()
        self.assertEqual(self.row(task), before)
        self.assertEqual(self.store.enqueue([self.job('pagination', kind='feed_page')]), 1)

    def test_enqueue_abort_recovers_and_rolls_back_earlier_batches(self):
        jobs = [self.job(str(number)) for number in range(500)]
        with self.assertRaises(psycopg2.IntegrityError):
            self.store.enqueue(jobs + [self.job('invalid', kind='invalid')])
        self.assertEqual(0, self.store.status()['due'])
        self.assertEqual(1, self.store.enqueue([self.job()]))
        self.assertEqual(1, len(self.store.claim()))
        with self.assertRaises(ValueError):
            self.store.enqueue([self.job('bad-payload', payload=[])])
        self.assertEqual(0, self.store.status()['due'])

    def test_claim_order_host_exclusion_and_due_times(self):
        self.store.enqueue([
            self.job('low', priority=1), self.job('high', priority=10),
            self.job('high', priority=5, url='https://high.example/other'),
            self.job('later', priority=100), self.job('tied', priority=1),
        ])
        self.query("UPDATE crawl_jobs SET due_at = NOW() + INTERVAL '1 day' WHERE host = 'later.example'")
        claimed = self.store.claim(8)
        self.assertEqual(['high.example', 'low.example', 'tied.example'], [job['host'] for job in claimed])
        self.assertEqual({'id', 'kind', 'url', 'host', 'priority', 'payload', 'attempts',
                          'lease_token', 'etag', 'last_modified', 'resolved_url'}, set(claimed[0]))
        self.assertTrue(all(job['attempts'] == 1 for job in claimed))
        self.assertEqual([], self.store.claim())
        self.assertTrue(self.store.complete(claimed[0]))
        self.assertEqual('https://high.example/other', self.store.claim(1)[0]['url'])
        self.assertEqual([], self.store.claim(0))

    def test_due_then_id_break_priority_ties(self):
        self.store.enqueue([self.job('first'), self.job('second'), self.job('oldest')])
        self.query("UPDATE crawl_jobs SET due_at = NOW() - INTERVAL '1 day' WHERE host = 'oldest.example'")
        self.assertEqual(['oldest.example', 'first.example', 'second.example'],
                         [job['host'] for job in self.store.claim()])

    def test_claim_does_not_starve_hosts_behind_a_large_single_host_backlog(self):
        self.store.enqueue([self.job(url='https://busy.example/' + str(number), priority=100)
                            for number in range(600)] + [self.job('second'), self.job('third')])
        claimed = self.store.claim(8)
        self.assertEqual(['busy.example', 'second.example', 'third.example'], [job['host'] for job in claimed])

    def test_shared_sitemap_and_archive_urls_are_scoped_to_the_root(self):
        roots = ['https://shared.example/alice/', 'https://shared.example/bob/']
        jobs = [self.job(kind=kind, url='https://shared.example/map', payload={'root': root, 'depth': 1})
                for root in roots for kind in ('sitemap', 'archive')]
        self.assertEqual(4, self.store.enqueue(jobs))
        self.assertEqual(0, self.store.enqueue(jobs))
        rows = self.query('SELECT scope, payload FROM crawl_jobs')
        self.assertEqual({sha256(root.encode()).hexdigest() for root in roots}, {row['scope'] for row in rows})
        self.assertTrue(all(row['scope'] == sha256(row['payload']['root'].encode()).hexdigest() for row in rows))
        for kind in ('feed', 'page'):
            self.assertEqual(1, self.store.enqueue([self.job(kind=kind, payload={'root': root}, priority=90) for root in roots]))
        self.assertTrue(all(row['scope'] == '' for row in self.query("SELECT scope FROM crawl_jobs WHERE kind IN ('feed', 'page')")))

    def test_budget_deduplicates_across_batches_and_exempts_fresh_entries(self):
        root = 'https://blog.example/'
        self.assertEqual(0, self.store.set_backfill_budget(root, budget=2))
        first = self.job('first', payload={'root': root})
        second = self.job('second', payload={'root': root})
        third = self.job('third', payload={'root': root})
        self.assertEqual(1, self.store.enqueue([first] * 501))
        self.assertEqual({'cap': 2, 'discovered': 1, 'limited': False},
                         self.query('SELECT cap, discovered, limited FROM crawl_sites')[0])
        self.assertEqual(1, self.store.enqueue([first, second, second]))
        self.assertFalse(self.query('SELECT limited FROM crawl_sites')[0]['limited'])
        self.assertEqual(0, self.store.enqueue([first, third]))
        self.assertEqual(1, self.store.status()['backfill_limited'])
        self.assertEqual(2, self.store.enqueue([self.job('feed', kind='feed', payload={'root': root}),
                                               {**third, 'priority': 90}]))
        self.assertEqual(0, self.store.enqueue([{**first, 'priority': 90}]))
        self.assertEqual(2, self.query('SELECT discovered FROM crawl_sites')[0]['discovered'])
        self.assertEqual(90, self.query('SELECT priority FROM crawl_jobs WHERE url = %s', (first['url'],))[0]['priority'])

    def test_budget_increase_resumes_discovery_and_clears_parent_validators(self):
        root = 'https://blog.example/'
        self.store.set_backfill_budget(root, 3)
        self.store.enqueue([self.job('blog', kind='archive', priority=40, payload={'root': root}),
                            self.job('blog', kind='sitemap', priority=30, payload={'root': root})])
        self.query("UPDATE crawl_jobs SET etag = 'old-tag', last_modified = 'old-date'")
        parent = self.store.claim(1)[0]
        children = [self.job(str(number), payload={'root': root, 'depth': 1}) for number in range(2)]
        self.store.complete(parent, links=children, etag='new-tag', last_modified='new-date')
        self.assertEqual(3, len(self.query('SELECT * FROM crawl_jobs')))
        self.assertIsNone(self.row(parent)['etag'])
        self.assertIsNone(self.row(parent)['last_modified'])
        self.assertEqual(1, self.store.status()['backfill_limited'])
        sitemap = self.store.claim(1)[0]
        running = self.row(sitemap)
        self.assertEqual(2, self.store.set_backfill_budget(root, 5))
        self.assertEqual(running, self.row(sitemap))
        self.assertEqual(0, self.store.status()['backfill_limited'])
        self.assertIsNone(self.row(parent)['etag'])
        self.store.complete(sitemap, not_modified=True)
        self.assertEqual(3, self.store.set_backfill_budget(root, 5))
        self.assertIsNone(self.row(sitemap)['etag'])
        self.assertIsNone(self.row(sitemap)['last_modified'])
        parent = self.store.claim(1)[0]
        self.store.complete(parent, links=children, etag='complete-tag')
        self.assertEqual(4, self.query('SELECT discovered FROM crawl_sites')[0]['discovered'])
        self.assertEqual('complete-tag', self.row(parent)['etag'])

    def test_default_budget_and_root_specific_reactivation(self):
        roots = ['https://shared.example/alice/', 'https://shared.example/bob/']
        self.store.enqueue([self.job(kind='sitemap', payload={'root': root}) for root in roots])
        self.query("UPDATE crawl_jobs SET due_at = NOW() + INTERVAL '30 days', etag = 'tag'")
        other = self.query('SELECT * FROM crawl_jobs WHERE scope = %s', (sha256(roots[1].encode()).hexdigest(),))[0]
        self.assertTrue(all(row['cap'] == 10000 for row in self.query('SELECT cap FROM crawl_sites')))
        self.assertEqual(1, self.store.set_backfill_budget(roots[0], 12000))
        self.assertEqual(other, self.query('SELECT * FROM crawl_jobs WHERE id = %s', (other['id'],))[0])
        self.assertEqual(roots[0], self.store.claim(1)[0]['payload']['root'])

    def test_backfill_resume_revisits_historical_pages_but_not_fresh_or_other_blogs(self):
        root = 'https://shared.example/alice/'
        tasks = [self.job('shared', url=root + 'chronicle/', priority=10, payload={'root': root}),
                 self.job('shared', url=root + 'new/', priority=90, payload={'root': root}),
                 self.job('shared', url='https://shared.example/bob/old/', priority=10,
                          payload={'root': 'https://shared.example/bob/'})]
        self.store.enqueue(tasks)
        self.query("UPDATE crawl_jobs SET due_at = NOW() + INTERVAL '30 days', etag = 'tag', last_modified = 'date'")
        before = self.query('SELECT * FROM crawl_jobs ORDER BY id')
        self.assertEqual(1, self.store.set_backfill_budget(root, 200))
        after = self.query('SELECT * FROM crawl_jobs ORDER BY id')
        self.assertIsNone(after[0]['etag'])
        self.assertIsNone(after[0]['last_modified'])
        self.assertEqual(before[1:], after[1:])
        self.assertEqual(tasks[0]['url'], self.store.claim(1)[0]['url'])

    def test_claims_are_exclusive_across_processes_and_normalize_hosts(self):
        self.store.enqueue([self.job(str(number), url='https://SHARED.example./' + str(number))
                            for number in range(8)] + [self.job('other')])
        context = multiprocessing.get_context('spawn')
        barrier, results = context.Barrier(2), context.Queue()
        workers = [context.Process(target=claim_in_process, args=(self.dsn, barrier, results)) for _ in range(2)]
        try:
            for worker in workers:
                worker.start()
            batches = [results.get(timeout=25) for _ in workers]
            for batch in batches:
                self.assertIsInstance(batch, list)
            claimed = [job for batch in batches for job in batch]
            self.assertEqual(2, len(claimed))
            self.assertEqual({'shared.example', 'other.example'}, {job['host'] for job in claimed})
            self.assertEqual([], self.store.claim())
        finally:
            for worker in workers:
                worker.join(timeout=5)
                if worker.is_alive():
                    worker.terminate()
                    worker.join(timeout=5)
            results.close()
            results.join_thread()

    def test_pool_supports_more_callers_than_connections(self):
        barrier = Barrier(8)
        def read_status(_):
            barrier.wait(timeout=10)
            return self.store.status()
        with ThreadPoolExecutor(max_workers=8) as executor:
            self.assertEqual([0] * 8, [result['due'] for result in executor.map(read_status, range(8))])
        self.assertEqual({}, self.store._pool._used)

    def test_expired_lease_and_stale_tokens_cannot_write(self):
        old = self.claimed()
        self.expire(old)
        self.assertFalse(self.store.complete(old, page=self.page(), links=[self.job('discovered')]))
        self.assertFalse(self.store.fail(old, 'too late'))
        fresh = self.store.claim(1)[0]
        self.assertEqual(old['id'], fresh['id'])
        self.assertNotEqual(old['lease_token'], fresh['lease_token'])
        self.assertEqual(2, fresh['attempts'])
        self.assertFalse(self.store.complete(old, page=self.page(), links=[self.job('discovered')]))
        self.assertFalse(self.store.fail(old, 'stale'))
        self.assertEqual([], self.query('SELECT * FROM pages'))
        self.assertEqual(1, len(self.query('SELECT * FROM crawl_jobs')))
        self.assertTrue(self.store.complete(fresh, page=self.page()))

    def test_expired_eighth_lease_fails_pages_but_feeds_keep_retrying(self):
        page = self.claimed()
        feed = self.claimed(name='feed', kind='feed')
        self.query("UPDATE crawl_jobs SET attempts = 8, lease_until = NOW() - INTERVAL '1 second'")
        claimed = self.store.claim()
        self.assertEqual([feed['id']], [job['id'] for job in claimed])
        self.assertEqual(9, claimed[0]['attempts'])
        self.assertEqual('failed', self.row(page)['status'])

    def test_success_schedules_recrawls_and_validators_follow_http_status(self):
        for kind, days in (('feed', 1), ('page', 30), ('sitemap', 30), ('archive', 30)):
            with self.subTest(kind=kind):
                job = self.claimed(name=kind, kind=kind)
                self.assertTrue(self.store.complete(job, etag='first', last_modified='yesterday'))
                self.assert_delay(job, days * 86400)
                self.assertEqual('pending', self.row(job)['status'])
                self.assertEqual(0, self.row(job)['attempts'])
                self.make_due(job)
                job = self.store.claim(1)[0]
                self.assertEqual(('first', 'yesterday'), (job['etag'], job['last_modified']))
                self.store.complete(job, not_modified=True, etag='ignored', last_modified='ignored')
                self.assertEqual(('first', 'yesterday'), (self.row(job)['etag'], self.row(job)['last_modified']))
                self.make_due(job)
                job = self.store.claim(1)[0]
                self.store.complete(job)
                self.assertIsNone(self.row(job)['etag'])
                self.assertIsNone(self.row(job)['last_modified'])

    def test_skip_and_explicit_page_reevaluation(self):
        page = self.claimed()
        self.query("UPDATE crawl_jobs SET etag = 'cached-tag', last_modified = 'cached-date' WHERE id = %s", (page['id'],))
        self.store.complete(page, skip_reason='no_extractable_text')
        feed = self.claimed(name='feed', kind='feed')
        self.store.complete(feed, skip_reason='blocked')
        self.assertEqual('skipped', self.row(page)['status'])
        self.assertIsNone(self.row(page)['last_success_at'])
        self.assert_delay(feed, 86400)
        self.make_due(page)
        self.assertEqual([], self.store.claim())
        self.assertEqual(0, self.store.retry_failed())
        self.assertEqual(1, self.store.retry_skipped())
        self.assertIsNone(self.row(page)['error'])
        self.assertIsNone(self.row(page)['etag'])
        self.assertIsNone(self.row(page)['last_modified'])
        self.assertEqual('skipped', self.row(feed)['status'])
        self.assertEqual(page['id'], self.store.claim(1)[0]['id'])
        self.make_due(feed)
        self.assertEqual(feed['id'], self.store.claim(1)[0]['id'])

    def test_extraction_retry_is_bounded_and_preserves_other_skips(self):
        for name, reason in (('empty-a', 'no_extractable_text'), ('empty-b', 'no_extractable_text'),
                             ('archive', 'archive_listing'), ('policy', 'noindex'),
                             ('contact', 'utility_page'), ('image', 'unsupported_content_type')):
            task = self.claimed(name=name)
            self.store.complete(task, skip_reason=reason)
        self.assertEqual(self.store.retry_skipped(limit=1), 1)
        skipped = self.query("SELECT error, COUNT(*) AS count FROM crawl_jobs WHERE status = 'skipped' GROUP BY error")
        self.assertEqual({row['error']: row['count'] for row in skipped}, {
            'no_extractable_text': 1, 'archive_listing': 1, 'noindex': 1,
            'utility_page': 1, 'unsupported_content_type': 1,
        })
        self.assertEqual(self.store.retry_skipped(limit=100), 1)
        self.assertEqual(self.store.retry_skipped(), 0)
        for limit in (0, -1):
            with self.assertRaises(ValueError):
                self.store.retry_skipped(limit=limit)

    def test_extraction_retry_leaves_removed_source_jobs_unchanged(self):
        source = self.source('removed')
        self.store.reconcile_sources([source])
        feed = self.store.claim(1)[0]
        self.store.complete(feed, links=[self.job('empty')])
        page = self.store.claim(1)[0]
        self.store.complete(page, skip_reason='no_extractable_text')
        self.store.reconcile_sources([self.source('retained')], excluded=[source['url']])
        before = self.row(page)
        self.assertEqual(self.store.retry_skipped(), 0)
        self.assertEqual(self.row(page), before)

    def test_run_level_deferral_refunds_attempt_and_preserves_content_and_validators(self):
        task, outbox = self.save()
        self.make_due(task)
        self.query("UPDATE crawl_jobs SET attempts = 7, etag = 'known', last_modified = 'yesterday' WHERE id = %s",
                   (task['id'],))
        task = self.store.claim(1)[0]
        self.assertEqual(task['attempts'], 8)
        self.assertTrue(self.store.defer(task, 'Crawler stopped: internal error'))
        row = self.row(task)
        self.assertEqual((row['status'], row['attempts'], row['etag'], row['last_modified']),
                         ('pending', 7, 'known', 'yesterday'))
        self.assertIsNone(row['lease_token'])
        self.assertIsNone(row['lease_until'])
        self.assert_delay(task, 300)
        self.assertIn('internal error', row['error'])
        self.assertEqual(self.store.index_batch(), [outbox])
        self.assertEqual(len(self.query('SELECT * FROM pages')), 1)
        self.assertFalse(self.store.defer(task, 'duplicate acknowledgement'))
        self.assertEqual(self.row(task), row)

    def test_run_level_deferral_cannot_release_an_expired_or_replaced_lease(self):
        old = self.claimed()
        self.expire(old)
        self.assertFalse(self.store.defer(old, 'expired'))
        current = self.store.claim(1)[0]
        before = self.row(current)
        self.assertFalse(self.store.defer(old, 'stale'))
        self.assertEqual(self.row(current), before)
        self.assertTrue(self.store.defer(current, 'current'))

    def test_run_level_deferral_respects_source_removal(self):
        source = self.source('removed')
        self.store.reconcile_sources([source])
        feed = self.store.claim(1)[0]
        self.store.reconcile_sources([self.source('retained')], excluded=[source['url']])
        self.assertFalse(self.store.defer(feed, 'run stopped'))
        self.assertNotEqual(self.row(feed)['status'], 'running')
        claimed = self.store.claim()
        self.assertNotIn(feed['id'], [task['id'] for task in claimed])

    def test_failure_backoff_preserves_retry_after_and_terminal_retries(self):
        job = self.claimed()
        for attempt in range(1, 9):
            self.assertEqual(attempt, job['attempts'])
            self.assertTrue(self.store.fail(job, 'temporary'))
            self.assert_delay(job, min(86400, 60 * 2 ** (attempt - 1)))
            self.assertEqual('failed' if attempt == 8 else 'pending', self.row(job)['status'])
            if attempt < 8:
                self.make_due(job)
                job = self.store.claim(1)[0]
        self.assertEqual([], self.store.claim())
        self.assertEqual(1, self.store.retry_failed())
        job = self.store.claim(1)[0]
        self.assertEqual(1, job['attempts'])
        self.store.fail(job, 'rate limited', retry_after=timedelta(days=10))
        self.assert_delay(job, 10 * 86400)
        self.make_due(job)
        self.query('UPDATE domains SET next_allowed_scrape = NOW() WHERE domain = %s', (job['host'],))
        job = self.store.claim(1)[0]
        self.store.fail(job, 'rate limited again', retry_after='7200')
        self.assert_delay(job, 7200)
        self.make_due(job)
        self.query('UPDATE domains SET next_allowed_scrape = NOW() WHERE domain = %s', (job['host'],))
        self.store.fail(self.store.claim(1)[0], 'permanent', retryable=False)
        self.assertEqual('failed', self.row(job)['status'])
        feed = self.claimed(name='feed', kind='feed')
        self.store.fail(feed, 'permanent feed failure', retryable=False)
        self.assertEqual('pending', self.row(feed)['status'])
        self.assert_delay(feed, 86400)
        self.make_due(feed)
        feed = self.store.claim(1)[0]
        self.query('UPDATE crawl_jobs SET attempts = 200 WHERE id = %s', (feed['id'],))
        self.store.fail(feed, 'still unavailable', retry_after=1)
        self.assertEqual('pending', self.row(feed)['status'])
        self.assert_delay(feed, 86400)

    def test_retry_after_and_http_429_cool_other_jobs_on_the_same_host(self):
        for host, retry_after, status_code in (('header', 120, None), ('429', None, 429)):
            with self.subTest(host=host):
                first = self.claimed(name=host, priority=100)
                self.store.enqueue([self.job(host, url='https://' + host + '.example/other')])
                self.store.fail(first, 'rate limited', retry_after=retry_after, status_code=status_code)
                self.assertEqual([], self.store.claim())
                self.store.enqueue([self.job(host + '-unrelated')])
                other = self.store.claim(1)[0]
                self.assertNotEqual(first['host'], other['host'])
                self.store.complete(other)
                self.query('UPDATE domains SET next_allowed_scrape = NOW() WHERE domain = %s', (first['host'],))
                next_job = self.store.claim(1)[0]
                self.assertEqual(first['host'], next_job['host'])
                self.store.complete(next_job)

    def test_host_cooldown_never_shortens_and_stale_failure_cannot_extend_it(self):
        job = self.claimed()
        self.query("INSERT INTO domains (domain, next_allowed_scrape) VALUES (%s, NOW() + INTERVAL '1 hour')", (job['host'],))
        before = self.query('SELECT next_allowed_scrape FROM domains')[0]
        self.store.fail(job, 'HTTP 429', retry_after=60, status_code=429)
        self.assertEqual(before, self.query('SELECT next_allowed_scrape FROM domains')[0])
        self.assertFalse(self.store.fail(job, 'stale', retry_after=86400))
        self.assertEqual(before, self.query('SELECT next_allowed_scrape FROM domains')[0])

    def test_redirect_cools_actual_destination_and_restores_from_database(self):
        task = self.claimed()
        self.store.fail(task, 'HTTP 429', status_code=429, retry_after=172800, host='destination.example')
        with Store(self.dsn) as restarted:
            cooldowns = restarted.host_cooldowns()
        self.assertNotIn(task['host'], cooldowns)
        self.assertAlmostEqual(cooldowns['destination.example'], 172800, delta=5)
        self.store.enqueue([self.job('destination')])
        self.assertEqual(self.store.claim(), [])

    def test_dead_feeds_are_rechecked_monthly_not_each_daily_run(self):
        for status in (404, 410):
            feed = self.claimed(name='feed' + str(status), kind='feed')
            self.store.fail(feed, 'HTTP error', retryable=False, status_code=status)
            self.assertEqual(self.row(feed)['status'], 'pending')
            self.assert_delay(feed, 30 * 86400)

    def test_robots_denials_are_monthly_for_feeds_and_posts_without_a_host_ban(self):
        for kind in ('feed', 'page'):
            with self.subTest(kind=kind):
                task = self.claimed(name=kind + '-robots', kind=kind)
                self.store.fail(task, 'Blocked by robots policy', retryable=False, failure_kind='robots_denied')
                self.assertEqual(self.row(task)['status'], 'pending')
                self.assertEqual(self.row(task)['attempts'], 0)
                self.assert_delay(task, 30 * 86400)
                self.assertEqual(self.store.claim(), [])
                # A blocked feed/path must not pause allowed paths on that host.
                allowed = self.job(kind + '-robots', url=task['url'] + '/allowed')
                self.store.enqueue([allowed])
                work = self.store.claim(1)[0]
                self.assertEqual(work['url'], allowed['url'])
                self.store.complete(work)
                self.assertEqual(self.store.host_cooldowns(), {})
                # Rediscovery does not bring the recheck forward.
                self.store.enqueue([self.job(kind + '-robots', kind=kind)])
                self.assert_delay(task, 30 * 86400)
                self.make_due(task)
                again = self.store.claim(1)[0]
                self.assertEqual(again['attempts'], 1)
                self.store.complete(again)

    def test_tls_failures_recheck_weekly_from_first_failure_and_survive_restart(self):
        for kind in ('feed', 'page'):
            with self.subTest(kind=kind):
                task = self.claimed(name=kind + '-tls', kind=kind)
                self.store.fail(task, 'TLS/certificate verification failed', failure_kind='tls_error')
                self.assertEqual(self.row(task)['status'], 'pending')
                self.assertEqual(self.row(task)['attempts'], 0)
                self.assert_delay(task, 7 * 86400)
                with Store(self.dsn) as restarted:
                    self.assertEqual(restarted.claim(), [])
                # Even a legacy job with exhausted burst retries gets a recheck.
                self.make_due(task)
                again = self.store.claim(1)[0]
                self.query('UPDATE crawl_jobs SET attempts = 20 WHERE id = %s', (again['id'],))
                self.store.fail(again, 'TLS failure', failure_kind='tls_error')
                self.assertEqual(self.row(task)['status'], 'pending')
                self.assertEqual(self.row(task)['attempts'], 0)
                self.assert_delay(task, 7 * 86400)

    def test_tls_recheck_does_not_turn_short_robots_cooldown_into_a_week_host_ban(self):
        task = self.claimed()
        self.store.fail(task, 'TLS failure fetching robots', failure_kind='tls_error', retry_after=300, host=task['host'])
        self.assert_delay(task, 7 * 86400)
        self.assertAlmostEqual(self.store.host_cooldowns()[task['host']], 300, delta=5)

    def test_policy_recheck_does_not_shorten_a_longer_server_retry_after(self):
        task = self.claimed()
        self.store.fail(task, 'deferred', failure_kind='robots_denied', retry_after=40 * 86400)
        self.assert_delay(task, 40 * 86400)

    def test_stale_lease_cannot_change_a_policy_recheck(self):
        task = self.claimed()
        self.store.fail(task, 'blocked', retryable=False, failure_kind='robots_denied')
        before = self.row(task)
        self.assertFalse(self.store.fail(task, 'stale tls failure', failure_kind='tls_error'))
        self.assertEqual(self.row(task), before)

    def test_migration_reschedules_only_legacy_robots_denials_and_is_idempotent(self):
        post = self.claimed(name='blocked-post')
        self.store.fail(post, 'Blocked by robots policy', retryable=False)
        feed = self.claimed(name='blocked-feed', kind='feed')
        self.store.fail(feed, 'Blocked by robots policy', retryable=False)
        dead = self.claimed(name='dead')
        self.store.fail(dead, 'HTTP status 404', retryable=False, status_code=404)
        dead_before = self.row(dead)
        running = self.claimed(name='running')
        self.query("UPDATE crawl_jobs SET error = 'Blocked by robots policy' WHERE id = %s", (running['id'],))
        running_before = self.row(running)
        self.store.migrate()
        for task in (post, feed):
            self.assertEqual(self.row(task)['status'], 'pending')
            self.assertEqual(self.row(task)['attempts'], 0)
            self.assert_delay(task, 30 * 86400)
        before = self.query('SELECT * FROM crawl_jobs ORDER BY id')
        self.store.migrate()
        self.assertEqual(self.query('SELECT * FROM crawl_jobs ORDER BY id'), before)
        self.assertEqual(self.row(dead), dead_before)
        self.assertEqual(self.row(running), running_before)

    def test_dead_post_tombstones_survive_rediscovery_and_backfill_resume(self):
        root = 'https://dead.example/'
        task = self.claimed(name='dead', priority=10, payload={'root': root})
        self.store.fail(task, 'HTTP 404', retryable=False, status_code=404)
        before = self.row(task)
        self.store.set_backfill_budget(root, 200)
        self.store.enqueue([self.job('dead', priority=90, payload={'root': root})])
        self.assertEqual(self.row(task)['status'], 'failed')
        self.assertEqual(self.row(task)['attempts'], before['attempts'])
        self.assertEqual(self.store.claim(), [])

    def test_exhausted_feed_cannot_override_a_long_retry_after(self):
        task = self.claimed(kind='feed')
        self.query('UPDATE crawl_jobs SET attempts = 20 WHERE id = %s', (task['id'],))
        self.store.fail(task, 'HTTP 503', retry_after=7 * 86400, status_code=503)
        self.assert_delay(task, 7 * 86400)

    def test_complete_rollback_includes_page_links_outbox_and_lease(self):
        job = self.claimed()
        before = self.row(job)
        original = self.store._save_page
        def broken(cursor, page, **kwargs):
            original(cursor, page, **kwargs)
            cursor.execute('SELECT 1 / 0')
        with patch.object(self.store, '_save_page', side_effect=broken):
            with self.assertRaises(psycopg2.DataError):
                self.store.complete(job, page=self.page(), links=[self.job('discovered', payload={'root': job['url']})])
        self.assertEqual(before, self.row(job))
        self.assertEqual([], self.query('SELECT * FROM pages'))
        self.assertEqual([], self.store.index_batch())
        self.assertEqual([], self.query('SELECT * FROM crawl_sites'))
        self.assertEqual(1, len(self.query('SELECT * FROM crawl_jobs')))
        self.assertTrue(self.store.complete(job, page=self.page(), links=[self.job('discovered')]))
        self.assertEqual(1, len(self.store.index_batch()))
        self.assertEqual(2, len(self.query('SELECT * FROM crawl_jobs')))

    def test_outbox_and_page_are_invisible_until_completion_commits(self):
        job = self.claimed()
        written, release = Event(), Event()
        original = self.store._save_page
        def pause(cursor, page, **kwargs):
            result = original(cursor, page, **kwargs)
            written.set()
            if not release.wait(timeout=15):
                raise TimeoutError('Test did not release transaction')
            return result
        with patch.object(self.store, '_save_page', side_effect=pause):
            with ThreadPoolExecutor(max_workers=1) as executor:
                future = executor.submit(self.store.complete, job, page=self.page(), links=[self.job('new')])
                try:
                    self.assertTrue(written.wait(timeout=10))
                    self.assertEqual([], self.store.index_batch())
                    self.assertEqual([], self.query('SELECT * FROM pages'))
                    self.assertEqual('running', self.row(job)['status'])
                    self.assertEqual(1, len(self.query('SELECT * FROM crawl_jobs')))
                finally:
                    release.set()
                self.assertTrue(future.result(timeout=10))
        self.assertEqual(1, len(self.store.index_batch()))
        self.assertEqual('pending', self.row(job)['status'])
        self.assertEqual({}, self.store._pool._used)

    def test_unchanged_fetch_only_touches_timestamp_and_304_does_not_index(self):
        job, indexed = self.save()
        self.store.index_done(indexed['page_id'], indexed['revision'])
        self.query("UPDATE pages SET scraped_on_date = '2000-01-01'")
        self.query("""CREATE FUNCTION reject_content_update() RETURNS trigger LANGUAGE plpgsql AS $$
                      BEGIN RAISE EXCEPTION 'Content must not be rewritten'; END $$""")
        self.query("""CREATE TRIGGER unchanged_content BEFORE UPDATE OF title, url, fingerprint, date, text
                      ON pages FOR EACH ROW EXECUTE FUNCTION reject_content_update()""")
        self.make_due(job)
        self.store.complete(self.store.claim(1)[0], page=self.page())
        self.assertEqual([], self.store.index_batch())
        self.assertGreater(self.query('SELECT scraped_on_date FROM pages')[0]['scraped_on_date'].year, 2000)
        self.query("UPDATE pages SET scraped_on_date = '2000-01-01'")
        self.make_due(job)
        self.store.complete(self.store.claim(1)[0], not_modified=True)
        self.assertEqual([], self.store.index_batch())
        self.assertGreater(self.query('SELECT scraped_on_date FROM pages')[0]['scraped_on_date'].year, 2000)

    def test_url_updates_reuse_id_and_stale_index_ack_cannot_remove_new_revision(self):
        job, old = self.save()
        self.make_due(job)
        self.store.complete(self.store.claim(1)[0], page=self.page(text='Edited text', fingerprint='edited'))
        new = self.store.index_batch()[0]
        self.assertEqual(old['page_id'], new['page_id'])
        self.assertGreater(new['revision'], old['revision'])
        self.assertEqual('Edited text', new['text'])
        self.assertEqual({'page_id', 'revision', 'operation', 'title', 'url', 'date', 'text', 'scraped_on_date'}, set(new))
        self.assertFalse(self.store.index_done(old['page_id'], old['revision']))
        self.assertFalse(self.store.index_failed(old['page_id'], old['revision'], 'stale'))
        self.assertTrue(self.store.index_done(new['page_id'], new['revision']))
        self.store.queue_reindex()
        latest = self.store.index_batch()[0]
        self.assertGreater(latest['revision'], new['revision'])
        self.assertFalse(self.store.index_done(new['page_id'], new['revision']))

    def test_reindex_waiting_after_sequence_allocation_still_increases_revision(self):
        job, _ = self.save()
        self.make_due(job)
        job = self.store.claim(1)[0]
        lock_id = uuid4().int % (2 ** 63)
        self.query("""CREATE FUNCTION pause_reindex() RETURNS trigger LANGUAGE plpgsql AS $$
                      BEGIN
                          IF current_setting('application_name') = %s THEN
                              PERFORM pg_advisory_xact_lock(%s);
                          END IF;
                          RETURN NEW;
                      END $$""", (self.schema, lock_id))
        self.query("""CREATE TRIGGER pause_reindex BEFORE INSERT ON crawl_index_jobs
                      FOR EACH ROW EXECUTE FUNCTION pause_reindex()""")
        with Store(make_dsn(self.dsn, application_name=self.schema)) as reindexer:
            self.query('SELECT pg_advisory_lock(%s)', (lock_id,))
            with ThreadPoolExecutor(max_workers=1) as executor:
                future = executor.submit(reindexer.queue_reindex)
                try:
                    deadline = time.monotonic() + 10
                    while not self.query("SELECT 1 FROM pg_stat_activity WHERE application_name = %s AND wait_event = 'advisory'",
                                         (self.schema,)):
                        if time.monotonic() >= deadline:
                            self.fail('Reindex did not reach the test barrier')
                        Event().wait(0.01)
                    self.store.complete(job, page=self.page(text='Edited', fingerprint='edited'))
                    updated = self.store.index_batch()[0]
                finally:
                    self.query('SELECT pg_advisory_unlock(%s)', (lock_id,))
                self.assertEqual(1, future.result(timeout=10))
        newest = self.store.index_batch()[0]
        self.assertEqual('Edited', newest['text'])
        self.assertGreater(newest['revision'], updated['revision'])
        self.assertFalse(self.store.index_done(updated['page_id'], updated['revision']))

    def test_finish_index_mixes_success_failure_and_stale_revisions(self):
        self.query("""INSERT INTO pages (url, fingerprint)
                      SELECT 'https://index.example/' || id, 'fingerprint-' || id FROM generate_series(1, 4) id""")
        self.store.queue_reindex()
        old = self.store.index_batch()
        self.store.queue_reindex()
        current = self.store.index_batch()
        before = self.query('SELECT * FROM crawl_index_jobs ORDER BY page_id')
        pair = lambda row: (row['page_id'], row['revision'])
        self.assertEqual(2, self.store.finish_index(
            [pair(current[0]), pair(old[2])],
            [(*pair(current[1]), 'ES unavailable'), (*pair(old[3]), 'stale failure')],
        ))
        remaining = self.query('SELECT * FROM crawl_index_jobs ORDER BY page_id')
        self.assertEqual(3, len(remaining))
        failed = remaining[0]
        self.assertEqual(current[1]['page_id'], failed['page_id'])
        self.assertEqual(current[1]['revision'], failed['revision'])
        self.assertEqual(1, failed['attempts'])
        self.assertEqual('ES unavailable', failed['error'])
        self.assertAlmostEqual(60, (failed['due_at'] - before[1]['due_at']).total_seconds(), delta=5)
        self.assertEqual(before[2:], remaining[1:])
        self.assertEqual([current[2], current[3]], self.store.index_batch())
        self.assertEqual(0, self.store.finish_index([], []))

    def test_finish_index_failure_rolls_back_successes_and_connection_recovers(self):
        self.query("""INSERT INTO pages (url, fingerprint)
                      SELECT 'https://index.example/' || id, 'fingerprint-' || id FROM generate_series(1, 2) id""")
        self.store.queue_reindex()
        first, second = self.store.index_batch()
        before = self.query('SELECT * FROM crawl_index_jobs ORDER BY page_id')
        self.query("""CREATE FUNCTION reject_index_failure() RETURNS trigger LANGUAGE plpgsql AS $$
                      BEGIN RAISE EXCEPTION 'Test failure after acknowledgement'; END $$""")
        self.query("""CREATE TRIGGER reject_index_failure BEFORE UPDATE ON crawl_index_jobs
                      FOR EACH ROW EXECUTE FUNCTION reject_index_failure()""")
        with self.assertRaises(psycopg2.errors.RaiseException):
            self.store.finish_index([(first['page_id'], first['revision'])],
                                    [(second['page_id'], second['revision'], 'ES failure')])
        self.assertEqual(before, self.query('SELECT * FROM crawl_index_jobs ORDER BY page_id'))
        self.assertTrue(self.store.index_done(first['page_id'], first['revision']))
        self.assertEqual({}, self.store._pool._used)

    def test_finish_index_batches_large_lists_and_preserves_backoff_cap(self):
        self.query("""INSERT INTO pages (url, fingerprint)
                      SELECT 'https://index.example/' || id, 'fingerprint-' || id FROM generate_series(1, 1002) id""")
        self.store.queue_reindex()
        rows = self.store.index_batch(1002)
        self.query('UPDATE crawl_index_jobs SET attempts = 20')
        successes = [(row['page_id'], row['revision']) for row in rows[:501]]
        failures = [(row['page_id'], row['revision'], 'ES unavailable') for row in rows[501:]]
        self.assertEqual(1002, self.store.finish_index(successes, failures))
        remaining = self.query('SELECT *, EXTRACT(EPOCH FROM due_at - NOW()) AS delay FROM crawl_index_jobs')
        self.assertEqual(501, len(remaining))
        self.assertTrue(all(row['attempts'] == 21 for row in remaining))
        self.assertTrue(all(abs(float(row['delay']) - 86400) < 5 for row in remaining))

    def test_redirected_page_304_refreshes_final_url_and_remembers_validator_target(self):
        task = self.claimed()
        final_url = 'https://destination.example/post/'
        self.store.complete(task, page=self.page(url=final_url), etag='"post"', resolved_url=final_url)
        self.assertEqual(self.row(task)['resolved_url'], final_url)
        self.query("UPDATE pages SET scraped_on_date = '2000-01-01'")
        self.make_due(task)
        again = self.store.claim(1)[0]
        self.assertEqual(again['resolved_url'], final_url)
        self.store.complete(again, not_modified=True)
        self.assertTrue(self.query("SELECT scraped_on_date > '2000-01-02' AS fresh FROM pages")[0]['fresh'])
        self.assertEqual(self.row(task)['resolved_url'], final_url)

    def test_http_slash_aliases_update_one_final_article_even_when_text_changes(self):
        final_url = 'https://article.example/post/'
        self.store.enqueue([self.job(url='http://article.example/post'), self.job(url=final_url)])
        first = self.store.claim(1)[0]
        self.store.complete(first, page=self.page(url=final_url), resolved_url=final_url)
        second = self.store.claim(1)[0]
        self.store.complete(second, page=self.page(url=final_url, text='An edited article', fingerprint='edited'),
                            resolved_url=final_url)
        self.assertEqual(self.query('SELECT url, text FROM pages'), [{'url': final_url, 'text': 'An edited article'}])
        self.assertEqual(self.store.status()['outbox'], 1)
        self.assertEqual(len(self.query('SELECT * FROM crawl_jobs')), 2)

    def test_identical_text_on_unrelated_urls_preserves_both_articles(self):
        _, indexed = self.save()
        self.store.index_done(indexed['page_id'], indexed['revision'])
        alias = self.claimed(name='alias')
        self.store.complete(alias, page=self.page(url=alias['url']))
        self.assertEqual(2, len(self.query('SELECT * FROM pages')))
        self.assertEqual(1, len(self.store.index_batch()))
        self.make_due(alias)
        self.store.complete(self.store.claim(1)[0], page=self.page(url=alias['url'], text='Changed article'))
        self.assertEqual([{'text': self.page()['text']}, {'text': 'Changed article'}],
                         self.query('SELECT text FROM pages ORDER BY id'))
        self.assertEqual('pending', self.row(alias)['status'])
        self.assertIsNone(self.row(alias)['error'])

    def test_concurrent_duplicate_pages_are_saved_once(self):
        first, second = self.claimed(), self.claimed(name='second')
        barrier = Barrier(2)
        def finish(job):
            with Store(self.dsn) as store:
                barrier.wait(timeout=10)
                return store.complete(job, page=self.page())
        with ThreadPoolExecutor(max_workers=2) as executor:
            self.assertEqual([True, True], list(executor.map(finish, (first, second))))
        self.assertEqual(1, len(self.query('SELECT * FROM pages')))
        self.assertEqual(1, len(self.store.index_batch()))

    def test_matching_text_only_merges_same_path_url_variants_and_alias_survives_edits(self):
        first_url = 'http://blog.example.org/article'
        second_url = 'https://blog.example.org/article/'
        first = self.claimed(url=first_url)
        self.store.complete(first, page=self.page(url=first_url))
        first_id = self.query('SELECT id FROM pages')[0]['id']
        second = self.claimed(url=second_url)
        self.store.complete(second, page=self.page(url=second_url))
        self.assertEqual(self.query('SELECT id,url FROM pages'), [{'id': first_id, 'url': second_url}])
        self.assertEqual(self.query('SELECT * FROM page_aliases'), [{'url': first_url, 'page_id': first_id}])
        self.make_due(first)
        self.store.complete(self.store.claim(1)[0], page=self.page(url=first_url, text='Edited article'))
        self.assertEqual(self.query('SELECT id,text FROM pages'), [{'id': first_id, 'text': 'Edited article'}])
        self.assertEqual(self.query('SELECT * FROM page_aliases'), [{'url': second_url, 'page_id': first_id}])

    def test_different_short_posts_on_same_host_are_not_merged(self):
        for slug in ('first', 'second'):
            url = 'https://blog.example.org/' + slug
            task = self.claimed(url=url)
            self.store.complete(task, page=self.page(url=url, text='Good morning!'))
        self.assertEqual(len(self.query('SELECT * FROM pages')), 2)

    def test_different_content_on_unproven_url_variants_is_not_merged(self):
        for url, text in (('http://blog.example.org/post', 'First content'),
                          ('https://blog.example.org/post/', 'Different content')):
            task = self.claimed(url=url)
            self.store.complete(task, page=self.page(url=url, text=text))
        self.assertEqual(len(self.query('SELECT * FROM pages')), 2)

    def test_redirect_of_existing_page_merges_ids_and_durably_deletes_old_index_entry(self):
        first = self.claimed(url='https://old.example.org/post')
        self.store.complete(first, page=self.page(url=first['url']))
        old_id = self.query('SELECT id FROM pages')[0]['id']
        second = self.claimed(url='https://new.example.org/post')
        self.store.complete(second, page=self.page(url=second['url'], text='Updated'))
        target_id = self.query('SELECT id FROM pages WHERE url = %s', (second['url'],))[0]['id']
        before = {row['page_id']: row for row in self.store.index_batch()}
        self.make_due(first)
        self.store.complete(self.store.claim(1)[0], page=self.page(url=second['url'], text='Newest'))
        self.assertEqual(self.query('SELECT id,text FROM pages'), [{'id': target_id, 'text': 'Newest'}])
        operations = {row['page_id']: row for row in self.store.index_batch()}
        self.assertEqual(operations[old_id]['operation'], 'delete')
        self.assertEqual(operations[target_id]['operation'], 'index')
        self.assertGreater(operations[old_id]['revision'], before[old_id]['revision'])
        self.assertFalse(self.store.index_done(old_id, before[old_id]['revision']))
        self.assertEqual(self.query('SELECT * FROM page_aliases'), [{'url': first['url'], 'page_id': target_id}])
        self.store.migrate()
        self.assertEqual(self.store.index_batch(), list(operations.values()))

    def test_new_titles_are_cleaned_even_when_caller_bypasses_extractor(self):
        task = self.claimed()
        self.store.complete(task, page=self.page(title='👩🏽‍💻  Hello'))
        self.assertEqual(self.query('SELECT title FROM pages'), [{'title': 'Hello'}])

    def test_304_can_refresh_a_remembered_alias_after_canonical_url_changes(self):
        first = self.claimed(url='https://blog.example.org/post')
        self.store.complete(first, page=self.page(url=first['url']), etag='old')
        second = self.claimed(url=first['url'] + '/')
        self.store.complete(second, page=self.page(url=second['url']))
        self.query("UPDATE pages SET scraped_on_date = '2000-01-01'")
        self.make_due(first)
        self.store.complete(self.store.claim(1)[0], not_modified=True)
        self.assertGreater(self.query('SELECT scraped_on_date FROM pages')[0]['scraped_on_date'].year, 2000)

    def test_reindex_failure_backoff_status_and_retry_scope(self):
        succeeded, indexed = self.save()
        for attempt in range(1, 14):
            self.assertTrue(self.store.index_failed(indexed['page_id'], indexed['revision'], 'ES down'))
            row = self.query('SELECT *, EXTRACT(EPOCH FROM due_at - NOW()) AS delay FROM crawl_index_jobs')[0]
            self.assertEqual(attempt, row['attempts'])
            self.assertAlmostEqual(min(86400, 60 * 2 ** (attempt - 1)), float(row['delay']), delta=5)
        self.assertEqual([], self.store.index_batch())
        failed = self.claimed(name='failed')
        self.store.fail(failed, 'permanent', retryable=False)
        pending = self.claimed(name='pending')
        self.store.fail(pending, 'temporary')
        running = self.claimed(name='running')
        skipped = self.claimed(name='skipped')
        self.store.complete(skipped, skip_reason='skip')
        before = [self.row(job) for job in (succeeded, pending, running, skipped)]
        status = self.store.status()
        json.dumps(status)
        self.assertEqual(1, status['outbox'])
        self.assertEqual(1, status['outbox_failed'])
        self.assertEqual(1, status['counts']['page']['failed'])
        self.assertEqual(1, status['counts']['page']['skipped'])
        self.assertIsNotNone(status['latest_success'])
        self.assertEqual(2, self.store.retry_failed())
        self.assertEqual(before, [self.row(job) for job in (succeeded, pending, running, skipped)])
        self.assertEqual(indexed['revision'], self.store.index_batch()[0]['revision'])
        self.assertEqual(0, self.store.status()['outbox_failed'])
        self.assertEqual(1, self.store.queue_reindex())
        newer = self.store.index_batch()[0]
        self.assertGreater(newer['revision'], indexed['revision'])
        self.assertFalse(self.store.index_failed(indexed['page_id'], indexed['revision'], 'late failure'))
        self.assertEqual(1, self.query('SELECT COUNT(*) AS count FROM pages')[0]['count'])


if __name__ == '__main__':
    unittest.main()
