name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/blogsearch:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}/blogsearch:${{ github.sha }} ghcr.io/${{ github.repository }}/blogsearch:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/blogsearch:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/blogsearch:latest

  deploy:
    name: Deploy to Prod
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/blog-search && git pull && docker compose -f compose.prod.yml pull && docker compose -f compose.prod.yml up -d

  # deploy:
  #   name: Deploy to Kubernetes
  #   needs: build_and_push
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy to Kubernetes
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           kubectl rollout restart deployment/blogsearch-deployment
  #           kubectl rollout status deployment/blogsearch-deployment
